name: CI for Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Cache Python dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 4: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt

    # Step 5: Install pytest separately (if needed)
    - name: Install pytest
      run: python -m pip install pytest

    # Step 6: Make tests.sh executable
    - name: Make tests.sh executable
      run: chmod +x ./project/tests.sh

    # Step 7: Run the tests
    - name: Run tests
      run: ./project/tests.sh
      shell: bash
